// import type { Metadata } from "next";
// // import { Inter } from "next/font/google";
// import "../shared/styles/globals.css";
// import Providers from "@/shared/utils/Provider";
// import localFont from "@next/font/local";
// import {ClerkProvider} from '@clerk/nextjs';


// const clashDisplay= localFont({
//   src: "../assets/fonts/ClashDisplay-Variable.ttf",
//   variable: "--font-calshDisplay",
//   weight:"700",
// })
// // const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//     <html lang="en">
//       <body className={'${clashDisplay.variable}'}>
     
//         <Providers>
//         {children}
//         </Providers>
        
//         </body>
//     </html>
//     </ClerkProvider>
//   );
// }



import type { Metadata } from "next";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import "../shared/styles/globals.css";
import Providers from "@/shared/utils/Provider";
import localFont from "@next/font/local";

const clashDisplay = localFont({
  src: "../assets/fonts/ClashDisplay-Variable.ttf",
  variable: "--font-clashDisplay",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={clashDisplay.variable}>
          <Providers>
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
            {children}
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}














//inter.className--> before adding font this was inside body tag classname properties 




//
// import {
//   ClerkProvider,
//   SignInButton,
//   SignedIn,
//   SignedOut,
//   UserButton
// } from '@clerk/nextjs'
// import './globals.css'
// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body>
//           <SignedOut>
//             <SignInButton />
//           </SignedOut>
//           <SignedIn>
//             <UserButton />
//           </SignedIn>
//           {children}
//         </body>
//       </html>
//     </ClerkProvider>
//   )
// }