import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "../shared/styles/globals.css";
import Providers from "@/shared/utils/Provider";
import localFont from "@next/font/local";


const clashDisplay= localFont({
  src: "../assets/fonts/ClashDisplay-variable.ttf",
  variable: "--font-calshDisplay",
  weight:"700",
})
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'${clashDisplay.variable}'}>
        <Providers>
        {children}
        </Providers>
        
        </body>
    </html>
  );
}
//inter.className--> before adding font this was inside body tag classname properties 
